### PR TITLE
Exclude generated classes from JaCoCo

### PR DESCRIPTION
**Pull request by j-esse**
Using same technique as FindBugs

### CODE REVIEW

**Comment by chrisalice** [comment]
Are we sure this won't accidentally break backwards compatibility with older Gradle versions?

**Comment by j-esse** [comment]
Good flag, I just tried it on 2.8 and it seems okay.  Is there something in particular you thought might be incompatible?   How old a version do you try to stay compatible with?

**Comment by chrisalice** [comment]
I generally dislike breaking people stuck on old tools unless it's totally unavoidable (e.g. FreeBuilder still supports Java 6). Unfortunately we don't automatically test this stuff as the testutils framework didn't exist, so we may already have broken backcompat, but this one raises a bigger red flag than usual because it's referencing a type that may not exist in old Gradle releases. If you could do a quick check of [2.3](https://github.com/gradle/gradle/releases/tag/REL_2.3) (2 years ago) and [1.11](https://github.com/gradle/gradle/releases/tag/REL_1.11) (3 years ago), that would be superb.

**Comment by chrisalice** [comment]
Also, we need an integration test to ensure this doesn't bit-rot.

**Comment by j-esse** [comment]
Thanks @chrisalice!  I looked into it, and JacocoReport was added to core Gradle in 1.6, before that it was in the gradle-jacoco plugin.  I changed it to try to find the class, and skip otherwise.

I tried it on Gradle 2.3, 1.11, and 1.6, and it seems to work fine.  (N.B. to run JaCoCo itself on 1.11 and 1.6 I had to use JDK 1.7 instead of 1.8, but that's a known JaCoCo issue in those versions; I also had to add a buildscript dependency on to get the gradle-processors plugin to work on 1.11 and 1.6, but that seems to be an existing issue).   On Gradle 1.5 it's a noop, but it doesn't break anything.

Also added an integration test.

**Comment by chrisalice** [comment]
Released as [v1.2.11](https://github.com/palantir/gradle-processors/releases/tag/v1.2.11).

**Pull request merged**
