### PR TITLE
Revert Findbugs workaround

### PR DESCRIPTION
**Pull request by henryptung**
Instead bump Immutables dependency to 2.1.12 to
leverage https://github.com/immutables/immutables/issues/263.

Targets #47, #49, #50.

### CODE REVIEW

**Comment by chrisalice** [comment]
Immutables isn't the only code generator in the world.

**Comment by henryptung** [comment]
@chrisalice Can you reference some examples? I think the fix could be easily propagated to the others, and I'd be happy to make that push.

As it stands, unfortunately `@Value.Enclosing` is quite broken because the generated class files reference other class files that are hidden from Findbugs, breaking the intended behavior there. Every time Findbugs currently runs in my project, it's outputting a big list of "Failed to find class X needed for analysis", and occasionally outputs real Findbugs warnings which I have no means to silence besides Findbugs filter hacks to match against the inner classes.

@j-baker @griechel Any specific throughts about this?

**Comment by chrisalice** [comment]
Off the top of my head, AutoValue, Dagger, FreeBuilder, Derive4J. Those are just the ones I've used; there are many more. I'd be surprised if they all accept a hack to work around a missing FindBugs feature.

**Comment by henryptung** [comment]
@chrisalice Understood; as a compromise, how about a configurable solution? The `ProcessorsPlugin` can expose a `ProcessorsExtension` extension that allows the workaround to be disabled if desired, to allow opt-out of the current behavior (with back-compat default).

Something like:

```
processors {
    suppressFindbugs = false
}
```

Of note, I don't know if there's a Checkstyle equivalent, as I don't think the current workaround applies to Checkstyle as it stands. If that's incorrect, please let me know, and I can add a `suppressCheckstyle` parameter as well.

**Comment by chrisalice** [comment]
Sounds good to me. Don't forget the tests.

**Pull request closed without merging**
