### PR TITLE
Update Gradle version to 2.12

### PR DESCRIPTION
**Pull request by nmiyake**
Updates Gradle version and wrapper binaries
and updates tests to conform to API breaks
introduced between the versions.

### CODE REVIEW

**Comment by nmiyake** [comment]
@chrisalice

**Comment by chrisalice** [comment]
Could you pull the latest changes to develop, just so I can be sure your new tests still pass?

**Comment by chrisalice** [comment]
This conflicts with develop after merging your other PRs.

**Comment by nmiyake** [comment]
Thanks; updated to fix merge conflict

**Pull request merged**
